### ISSUE TITLE
Suggestion: Contribution Guidelines & Project Organization

### ISSUE THREAD

**Issue by jan-krecke** [elizabeth-oda/the-heck#2]
# Overview

As announced in the comment on PR #1, I'll share some ideas on contributing and general project organization.

I'm basically just thinking out loud, so feel free to question everything I write :smiley: 

# Project Organization

- add unit tests
- automatic CI (e.g., with [GitHub Actions](https://docs.github.com/en/actions))
- issue templates: create some basic templates for some common categories (bug report, feature request, etc.)
- PR template: create a template with some helpful sections (e.g., 'Rationale', 'How has this been tested?', 'Close issue #xyz', a checklist with some mandatory to-dos such as e.g., 'I am sure that this PR is in line with the project goals', 'I have complied with the projects' code style etc.)
- labels: makes it easy to group issues and PRs by topic
- add a [license](https://choosealicense.com/) to make clear who can do what with your software 

# Contribution Guidelines

Some suggestions on how a `CONTRIBUTING.md` could look like (would need to be 'fluffed out' for actual use of course:

------------------------------------------------------------
If you want to contribute to this project, do the following

-  Make a fork of this repository
- Clone it to your local machine with
    ```
   git clone ...
   ```
- set origin and upstream, if not set by default
- create a feature branch with (for example) 
    ```
    git checkout -b your-name/the-feature
    ```
- make your changes and add relevant unit tests in the `tests.rs` (or whatever) module
- if all tests pass locally, commit and push your changes to your fork
- create a PR from your fork to this PR. Make sure that the CI passes.
------------------------------------------------------------

I think it would be good to have a list of known issues and hot topics, which could/should also go into `CONTRIBUTING.md`. Some things I can think of:

- enable  support for all shells and history files
- improve program candidates (e.g., by looking through directories on `$PATH` instead of using a hard-coded list of names
- handle commands consisting of a single word (`heck` panics for me when my last command is a single word like `ls`)
- better error handling: the issue above happens for me with a hard to interpret panic message:
    ```
    thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/lib.rs:8:31
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    ```
- etc

**Comment by elizabeth-oda** [comment]
@jan-krecke Thanks, and sorry for the delay. 
Basically, I agree with all of your suggestions. Let me make a PR for this and add you as a reviewer.
